package com.myspace.btpns_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class application implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public application() {
    }




}